### ISSUE TITLE
Question about `num_frames` and `cast_num_frames`

### ISSUE THREAD

**Issue by benearnthof** [ibrahimethemhamamci/GenerateCT#10]
Hello and thank you for this super useful repository! 
I'm currently comparing your implementation to the phenaki pytorch implementation you linked in the sources and have a question about the `cast_num_frames` function: 

```python
def cast_num_frames(t, *, frames):
    f = t.shape[1]
    if f%frames==0:
        return t[:,:-(frames-1)]
    if f%frames==1:
        return t
    else:
        return t[:,:-((f%frames)-1)]
```

This version coupled with the num_frames from the training config will always result in an uneven number of frames for training, since the third case cannot ever happen if `frames` is set to 2.  

My question is now if this is necessary or if this is just a shorthand to always train on videos of 201 frames length as you specified in the paper. The original implementation used in repos such as phenaki_pytorch or video_diffusion_pytorch uses:   
```python
def cast_num_frames(t, *, frames):
    f = t.shape[1]
    if f == frames:
        return t
    if f > frames:
        return t[:, :frames]
    return F.pad(t, (0, 0, 0, 0, 0, frames - f))
```

To only return a desired number of frames. 

Thanks again, I hope you can provide some insight into why we need an uneven number of frames.

**Comment by sezginerr** [comment]
Hello @benearnthof,

You're correct in noting that our `cast_num_frames` function invariably yields an odd number of frames. This odd frame count is crucial due to the encoder's architecture (both for our code and the Phenaki implementation). Training models with images and videos requires a unique encoding for the initial frame, different from subsequent frames. These latter frames use a time patch size, set at 2 in our case. Consequently, the total frame count minus one must be divisible by the time patch size. While the Lucid implementation limits to a maximum of 17 frames, slicing any excess, our approach doesn't strictly confine the model to 201 frames. We aim to ensure the frame count is odd, avoiding reliance on a specific frame count. There is a way to group the same number of frames in the same batch in the dataloader if you have a variable number of frames. So, we want to train models with variable frame counts if necessary. I also agree that the third case in our implementation is unnecessary. I'll commit changes to remove it and modify the function to accommodate different time patch sizes (it seems like it currently only works for a patch size of 2). Hope this answers your question!

**Comment by benearnthof** [comment]
Hi, thanks for clearing this up, I went through the phenaki implementation and saw that it requires an uneven amount of frames. I've used this code to train an encoder decoder pair with 128x128x131 resolution successfully, but the additional info in your comment helps a lot, thanks!
