### ISSUE TITLE
Little question about separate the images frame

### ISSUE THREAD

**Issue by frank-miao** [ibrahimethemhamamci/GenerateCT#12]
Thanks for your wonderful work about generation of CT scans! I have read your paper and this repository, then have some minor questions.

I'm very curious about the code in 

https://github.com/ibrahimethemhamamci/GenerateCT/blob/b481a677b41ce114218a8d9c9be3d1a183e2b090/transformer_maskgit/transformer_maskgit/ctvit.py?plain=1#L516

Why do we need to divide the frame into the first frame and the rest?

**Comment by sezginerr** [comment]
Hi @frank-miao, you do not have to do that. This is done (similarly in phenaki as well), however, to tokenize the first frame separately than the other frames (other frames are patched in axial slices but first frame is not). This is useful in future directions that a single generation model trained to generate both 2D and 3D medical images (this should be discussed in discussion of the paper). But for CT generation specifically you do not need it. In CT-CLIP for example, we use similar encoder but do not tokenize first frame separately. I hope this helps.

**Comment by frank-miao** [comment]
Thanks for your insightful reply! Still, I have some questions.

1. So in GenerateCT, is the frame dimension 201 carefully designed? Since I haven't seen such a strange number in the field of deep learning.
2. I took some time read the repository of CT-CLIP, you construct your CT-ViT in a different set of parameters (the image size, frame size, patch size)
https://github.com/ibrahimethemhamamci/CT-CLIP/blob/2d0a9d30e67762f56cd03e0a3d3c34d8a13712d0/scripts/run_train.py#L18-L28
and
https://github.com/ibrahimethemhamamci/GenerateCT/blob/b481a677b41ce114218a8d9c9be3d1a183e2b090/train_ctvit.py#L4-L14

I wonder if this will affect its performance since you freeze your parameters during training?

**Comment by sezginerr** [comment]
Hi @frank-miao,

Thank you for your comments.

1. I agree, it is not usual in this field. Because of the separate encoding of the first frame, the number of frames minus 1 should be divisible by the temporal patch size (here 2). Therefore, in this setting, the provided number of frames should be an odd number. Using 201 covers most of the CT volumes without increasing computational requirements too much, which is why we chose it. Though the model can accept any odd number of frames with the correct dataloader settings, putting the same number of slices into the same batch. We have been working on training a model that can generate a variable number of slices.

2. Yes, settings are different in CT-CLIP, as x-y patches are more important than axial patches in CLIP settings (encoding of small pathologies will be problematic otherwise). This is not the case in generatect as we already encode-decode smaller volumes, then we apply superresolution for small pathologies. CLIP training trains the encoder from scratch, and weights are not frozen during CLIP training.

I hope this helps.

**Comment by frank-miao** [comment]
@sezginerr Thanks for your insightful explanation and this really helps me very, very much. I think I have learned a lot from your project and your reply.

Since I have figured out these problems, I will close the issue.

Thanks again for taking so much time to answer my question!
